<%@ page language="java" contentType="text/html; charset=ISO-8859-1"%>
<!-- This .jsp produces a page of links to each model under this context root, for development use only. -->
<!-- Do not deploy this JSP with your production WARs, since users should have no use for a list of your models. -->

<!-- 
Licensed Materials Property of IBM 
5724-O03
(C) Copyright 2004, 2006. IBM Corp. All rights reserved.
US Government Users Restricted Rights. Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
-->

<%@ page import="java.util.Date" %>
<%@ page import="java.io.File" %>
<%@ page import="java.text.SimpleDateFormat" %>
<%@ page import="com.bowstreet.BSConfig" %>
<%@ page import="com.bowstreet.util.filecollection.*" %>
<html>
<body bgcolor="white">
<h1> Available Models </h1>

The following models are contained under the \WEB-INF\models\ directory of the project 
and may be run by using the links below.  You may also run a model in the project through 
the following steps:
<OL>
<LI>Open the model – all models are located under the \WEB-INF\models\ directory of your project.
<LI>Choose the Run &gt; Run… menu option
<LI>In the Run dialog, select a IBM Model configuration and click the Run button (create 
a new one if necessary).
<LI>Your model will launch in a separate browser window.
</OL>

<font size="4">
<%
	String subdir = "samples";
	boolean gotsample = false;
        String modeldir = BSConfig.getHtmlRootDir() + File.separator + "WEB-INF" + File.separator + "models";
        FileEntryIterator f = FileEntryIterator.getInstance(modeldir + File.separator + subdir);
        if (f!=null)
        while (f.hasNext())
        {
            FileEntryIterator.Entry e = (FileEntryIterator.Entry)(f.next());
            String name = e.getName();
            try { e.getStream().close(); } catch (Exception ioe){}
            int pos = name.lastIndexOf(".");
            if (pos == -1)
            	continue;	// expect ".model"
            String extn = name.substring(pos+1);
            if (!extn.equals("model"))
            	continue;
            name = subdir + File.separator + name.substring(0,pos);
            if (name.endsWith("NewBuilderWizard"))
            	continue;
            if (!gotsample)
            		out.println("<BR><H2>Sample Models</H2><HR>");
            if (File.separator.equals("\\"))
            	name = name.replace('\\','/');            		
            out.println("<a href='" + request.getContextPath() + "/webengine/" + name + "'>" + name + "</a><BR>"); 
            gotsample = true;
        }
        out.println("<BR><H2>Models</H2><HR>");
        
%>
</font>
<font size="4">
<%
        f = FileEntryIterator.getInstance(modeldir);
        if (f!=null)
        while (f.hasNext())
        {
            FileEntryIterator.Entry e = (FileEntryIterator.Entry)(f.next());
            String name = e.getName();
            try { e.getStream().close(); } catch (Exception ioe){}
            int pos = name.lastIndexOf(".");
            if (pos == -1)
            	continue;	// expect ".model"
            if (name.startsWith("samples" + File.separator))
            	continue;
            String extn = name.substring(pos+1);
            if (!extn.equals("model"))
            	continue;
            name = name.substring(0,pos);
            if (File.separator.equals("\\"))
            	name = name.replace('\\','/');            		
            out.println("<a href='" + request.getContextPath() + "/webengine/" + name + "'>" + name + "</a><BR>"); 
        }
%>
</font>
<br>
<font size="2">
<%
	SimpleDateFormat formatter = new SimpleDateFormat("EEE, MMM d, yyyy 'at' HH:mm:ss  zzz");
 	Date currentTime_1 = new Date();
 	String dateString = "generated by &quot;index.jsp&quot;, version 4, " + formatter.format(currentTime_1);
	out.println(dateString);
%>
</font>
</body>
</html>
