<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:tns="http://LoginValidation" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="LoginValidation" targetNamespace="http://LoginValidation">
	<wsdl:documentation>
		<wsdl:appinfo source="WMQI_APPINFO">
			<MRWSDLAppInfo imported="true">
				<generatedXSD location="LoginValidation_InlineSchema1.xsd" />
				<binding hasEncoding="false" imported="true"
					name="LoginValidationHttpBinding" originalBindingStyle="document" />
			</MRWSDLAppInfo>
		</wsdl:appinfo>
	</wsdl:documentation>
	<wsdl:types>
		<xsd:schema targetNamespace="http://LoginValidation">
			<xsd:import
				schemaLocation="http://172.16.11.225:7800/LoginValidation/LoginValidation?xsd=xsd0" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="operation1RequestMsg">
		<wsdl:part element="tns:operation1" name="operation1Parameters" />
	</wsdl:message>
	<wsdl:message name="operation1ResponseMsg">
		<wsdl:part element="tns:operation1Response" name="operation1Result" />
	</wsdl:message>
	<wsdl:portType name="LoginValidation">
		<wsdl:operation name="operation1">
			<wsdl:input message="tns:operation1RequestMsg" name="operation1Request" />
			<wsdl:output message="tns:operation1ResponseMsg" name="operation1Response" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="LoginValidationHttpBinding" type="tns:LoginValidation">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="operation1">
			<soap:operation soapAction="http://LoginValidation/operation1" />
			<wsdl:input name="operation1Request">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="operation1Response">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="LoginValidationHttpService">
		<wsdl:port binding="tns:LoginValidationHttpBinding" name="LoginValidationHttpPort">
			<soap:address
				location="http://172.16.11.225:7800/LoginValidation/LoginValidation" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>