/**
 * Description:  WEF builder regen class
 *
 * Licensed Materials - Property of IBM 
 * 5724-O03
 * (C) Copyright 2012. IBM Corp. All rights reserved.
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 * See Web Experience Factory ( product id 5724-O03 ) product license for terms and conditions of use. 
 *
 * This Java source file was generated by the Web Experience Factory.
 *
 * Do not edit generated code within the following comments /*##GENERATED_...
 */
import com.bowstreet.webapp.*;
import com.bowstreet.generation.*;
import com.bowstreet.util.*;
import com.bowstreet.builders.webapp.foundation.*;
import com.bowstreet.builders.webapp.pagelocation.*;
import com.bowstreet.builders.webapp.api.*;
import com.bowstreet.builders.webapp.methods.BuilderHelperUtil;

/**
 * Bowstreet builder regen class for page control builder
 */
public class ClassName implements WebAppControlBuilder
{

    /**
     * Interface that has constants for all the builder input names
     */
    static public interface Constants
    {
	}

    /**
     * This is the method that's called during generation of the WebApp.
     */
    public void doBuilderCall(GenContext genContext, WebApp webApp, BuilderCall builderCall,
            BuilderInputs builderInputs, PageLocation pageLocation)
    {
        // System.out.println("builderInputs: " + builderInputs);
        /*##GENERATED_BODY_BEGIN#InputAccessorCode#*/
        /*##GENERATED_BODY_END*/

        // Example of calling the Text builder to insert some HTML or JSP at specified location
        // All the callable builders are in the com.bowstreet.builders.webapp.api package
        Text textBuilder = new Text(builderCall, genContext);
        textBuilder.setPageLocation(pageLocation);
        textBuilder.setText("Hello builder world!");
        textBuilder.invokeBuilder();

	}
}

